### ISSUE TITLE
Error compilin a new configuration t85

### ISSUE THREAD

**Issue by freskpe** [ArminJo/micronucleus-firmware#19]
Hello! I'm trying to compile a new configuration (ENTRY_JUMPER) on attiny85 but i got the next error... 
![image](https://user-images.githubusercontent.com/24432922/113644550-01b4a500-9653-11eb-9ee4-6d2a06c4f727.png)

I'm using
Ubuntu 20.04
GNU Make 4.2.1
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Thank you in advance!

**Comment by RaduTek** [comment]
I am getting the same error when using ENTRY_JUMPER but if I select other configurations it all compiles just fine. I'm unfortunately lacking the knowledge to help. I'm compiling on Windows 10 20H2 with Arduino 1.8.13 and the latest version of the board package from @ArminJo.

To add, my attempts error out at address 0x2006 instead of 0x2004 but I don't think that's an issue.

>  **********************************************************
> 
> make Configuration t85_default
> **********************************************************
> c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: address 0x2006 of main.bin section `.text' is not within region `text'
> c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: address 0x2006 of main.bin section `.text' is not within region `text'
> collect2.exe: error: ld returned 1 exit status
> make: *** [main.bin] Error 1

**Comment by RaduTek** [comment]
After some more "analysis" I found that the line 181 in bootloaderconfig.h seems to cause the compile error.
`  #define bootLoaderInit()   {JUMPER_DDR &= ~_BV(JUMPER_PIN); JUMPER_PORT |= _BV(JUMPER_PIN); _delay_ms(1);}`
this line is supposed to set the pullup on the jumper pin and add a delay to let the input stabilize so the pin isnt floating, so it can't be removed.

Since I'm not knowledgeable at coding for AVRs directly without Arduino, I'm not sure if there's something to fix here. Looking at some info online it seems like the pin declarations are OK. _BV(x) is just a macro for (1 << x)

**Comment by RaduTek** [comment]
Interesting, after removing the `_delay_ms(1);` now the code compiles. I have uploaded it onto my Digispark and behavior is as expected. So to do this go to line 181 and comment out `_delay_ms(1);`. Then it will compile just fine.

I hope someone with more experience can clarify what the real problem is here and what a better fix would be.

**Comment by freskpe** [comment]
i'm was trying to compile another options (like ENTRY_ALWAYS) and i'm getting the same error, i think that the problem could be the compiler or another thing that i no know.

**Comment by RaduTek** [comment]
Well I'm compiling on Windows so not sure if I can help with that, but try to use the `t85_default` config and modify the bootloader config in `configuration/t85_default/bootloaderconfig.h`. That's what I did. Also the latest repository version doesn't even have a `t85_jumper` config.

**Comment by ArminJo** [comment]
If changes to the configuration lead to an increase in bootloader size, ie you see errors like `address 0x2026 of main.bin section '.text' is not within region 'text'`, it may be necessary to change/decrease the bootloader start address as described [above](#computing-the-values) or in the *Makefile.inc*.

delay can be omitted to save memory, if external capacitance at the jumper pin is low
